// Generated by design/mascot/gen3d/key.py — do not edit by hand.
// Frames live in public/mascot3d/<name>.webp (+ <name>.sm.webp at half size).
// An empty SEAL3D_FRAMES list makes Seal3D fall back to the 2D SVG mascot.

export const SEAL3D_FRAMES: readonly string[] = ["read-happy", "read-happy-blink", "read-joy", "read-neutral", "read-neutral-blink", "stand-happy", "stand-happy-blink", "stand-joy", "stand-neutral", "stand-neutral-blink", "stand-sad", "stand-sad-blink", "stand-surprised", "stand-surprised-blink", "stand-wink", "wave-happy", "wave-happy-b", "wave-happy-blink", "wave-joy", "wave-joy-b", "wave-love", "wave-love-b", "wave-surprised", "wave-surprised-b", "wave-surprised-blink", "wave-wink", "wave-wink-b"];

/** Frame size (px, full resolution) and landmarks inside it. */
export const SEAL3D_CANVAS = { w: 794, h: 1034, baseline: 1016, headTop: 16, cx: 397, bodyH: 1000, feetW: 498, feetCx: 416 };

export const SEAL3D_ICE: { w: number; h: number } | null = { w: 1200, h: 592 };

/** Contact shadow per pose (public/mascot3d/shadow-<pose>.webp): frame-wide, from `top` (frame px) down `h` px. */
export const SEAL3D_SHADOW: { poses: readonly string[]; top: number; h: number } | null = { poses: ["read", "stand", "wave"], top: 926, h: 130 };

/** Cache buster: changes whenever a frame changes. */
export const SEAL3D_VERSION = "86acc3a0";
